version: "3.9"
services:
  db:
    image: postgres:14
    container_name: advcompro
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: equipment_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: ./api
    container_name: rai_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./api:/app

  frontend:
    build: ./nextjs
    container_name: rai_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs:/src
      - /src/node_modules
    working_dir: /src
    command: npm run dev
    depends_on:
      - api

volumes:
  db_data:
