import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import AppBarWrapper from "@/components/AppBarWrapper";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
<<<<<<< HEAD
  title: "L'Heure Bleue",
=======
  title: "L'heure bleue",
>>>>>>> b423f6a0d2af9b49928a83c8b3505cf7045503e4
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AppBarWrapper />
        {children}
      </body>
    </html>
  );
}
